// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalTrabajo.DAL.DBContext;

#nullable disable

namespace PortalTrabajo.DAL.Migrations
{
    [DbContext(typeof(PortalTrabajoDbContext))]
    partial class PortalTrabajoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfertaCarrera", b =>
                {
                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.HasKey("OfertaId", "CarreraId")
                        .HasName("PK__OfertaCa__F186AF337FFF2F6D");

                    b.HasIndex("CarreraId");

                    b.ToTable("OfertaCarreras", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.AlumnosActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Carrera")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EstadoAcademico")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("Facultad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordPortal")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__AlumnosA__3214EC079F28C4A9");

                    b.HasIndex(new[] { "Carnet" }, "UQ__AlumnosA__5E387B4D6173647D")
                        .IsUnique();

                    b.ToTable("AlumnosActivos", "PortalNotasMock");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Facultad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__CatCarre__3214EC0719BD5C92");

                    b.ToTable("CatCarreras");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__CatDepar__3214EC073E894DBC");

                    b.ToTable("CatDepartamentos");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatDistrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__CatDistr__3214EC07C01AA7A4");

                    b.HasIndex("MunicipioId");

                    b.ToTable("CatDistritos");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatEstadosPostulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CatEstad__3214EC07D59106FC");

                    b.ToTable("CatEstadosPostulacion", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatGenero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__CatGener__3214EC071D80B2F5");

                    b.ToTable("CatGeneros");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatGradosAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__CatGrado__3214EC0723A16B8D");

                    b.ToTable("CatGradosAcademicos");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatModalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CatModal__3214EC071ECA6E8C");

                    b.ToTable("CatModalidades");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatMunicipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__CatMunic__3214EC074298774A");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("CatMunicipios");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatNivelesIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CatNivel__3214EC07303040D3");

                    b.ToTable("CatNivelesIdioma", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CatRoles__3214EC072D9429AC");

                    b.ToTable("CatRoles");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CatSectores", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatTiposContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CatTipos__3214EC0731A7648D");

                    b.ToTable("CatTiposContrato", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatTiposLicencium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CatTipos__3214EC07049DC62F");

                    b.ToTable("CatTiposLicencia");
                });

            modelBuilder.Entity("PortalTrabajo.Model.ContactosEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dui")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DUI");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TelefonoMovil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Contacto__3214EC0768A6AAE4");

                    b.HasIndex(new[] { "EmpresaId" }, "UQ__Contacto__7B9F21175146502A")
                        .IsUnique();

                    b.ToTable("ContactosEmpresa", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.Educacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("GradoAcademicoId")
                        .HasColumnType("int");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("TituloObtenido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Educacio__3214EC0726CD9B68");

                    b.HasIndex("GradoAcademicoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("Educacion", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Nit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NIT");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("SectorId");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Twitter")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Empresas__3214EC072876EC97");

                    b.HasIndex("SectorId");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ__Empresas__2B3DE7B99A6E4E70")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("PortalTrabajo.Model.EstudianteHabilidade", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("int");

                    b.Property<int?>("NivelDominio")
                        .HasColumnType("int");

                    b.HasKey("PerfilId", "HabilidadId")
                        .HasName("PK__Estudian__3B3444E48BFCED8D");

                    b.HasIndex("HabilidadId");

                    b.ToTable("EstudianteHabilidades");
                });

            modelBuilder.Entity("PortalTrabajo.Model.EstudianteIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Estudian__3214EC07ACD1740A");

                    b.HasIndex("NivelId");

                    b.HasIndex("PerfilId");

                    b.ToTable("EstudianteIdiomas");
                });

            modelBuilder.Entity("PortalTrabajo.Model.ExperienciasLaborale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DescripcionPuesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("EsTrabajoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Experien__3214EC0708A94314");

                    b.HasIndex("PerfilId");

                    b.ToTable("ExperienciasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Habilida__3214EC0799335888");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("PortalTrabajo.Model.OfertaHabilidade", b =>
                {
                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("int");

                    b.Property<bool?>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("OfertaId", "HabilidadId")
                        .HasName("PK__OfertaHa__C5568BCB41F49F68");

                    b.HasIndex("HabilidadId");

                    b.ToTable("OfertaHabilidades");
                });

            modelBuilder.Entity("PortalTrabajo.Model.OfertasLaborale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistritoId")
                        .HasColumnType("int");

                    b.Property<int?>("EdadMax")
                        .HasColumnType("int");

                    b.Property<int?>("EdadMin")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int?>("LicenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Requisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalarioMax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("SalarioMin")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("TieneVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("TipoContratoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Vacantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__OfertasL__3214EC073DAF7E5D");

                    b.HasIndex("DistritoId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("LicenciaId");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("TipoContratoId");

                    b.HasIndex(new[] { "Activa", "FechaExpiracion" }, "IX_Ofertas_Activa");

                    b.HasIndex(new[] { "EmpresaId" }, "IX_Ofertas_EmpresaId");

                    b.ToTable("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.PerfilesEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("BuscaEmpleo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EnlaceGitHub")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("EnlaceLinkedIn")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SobreMi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Perfiles__3214EC0725DCF04E");

                    b.HasIndex("CarreraId");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ__Perfiles__2B3DE7B9779DB5CD")
                        .IsUnique();

                    b.HasIndex(new[] { "Carnet" }, "UQ__Perfiles__5E387B4D0887FBB9")
                        .IsUnique();

                    b.ToTable("PerfilesEstudiantes");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Postulacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaPostulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Postulac__3214EC079C1BB18B");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PerfilId");

                    b.HasIndex(new[] { "OfertaId", "PerfilId" }, "UQ_Postulacion_Oferta_Perfil")
                        .IsUnique();

                    b.ToTable("Postulaciones");
                });

            modelBuilder.Entity("PortalTrabajo.Model.ProyectosEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnlaceRepositorio")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateOnly?>("FechaProyecto")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("TecnologiasUsadas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Proyecto__3214EC07E99BA583");

                    b.HasIndex("PerfilId");

                    b.ToTable("ProyectosEstudiante", (string)null);
                });

            modelBuilder.Entity("PortalTrabajo.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07F7DA8A0D");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534FB1CB407")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OfertaCarrera", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatCarrera", null)
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfertaCarreras_Carrera");

                    b.HasOne("PortalTrabajo.Model.OfertasLaborale", null)
                        .WithMany()
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfertaCarreras_Oferta");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatDistrito", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatMunicipio", "Municipio")
                        .WithMany("CatDistritos")
                        .HasForeignKey("MunicipioId")
                        .IsRequired()
                        .HasConstraintName("FK_Distritos_Municipio");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatMunicipio", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatDepartamento", "Departamento")
                        .WithMany("CatMunicipios")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK__CatMunici__Depar__3E1D39E1");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("PortalTrabajo.Model.ContactosEmpresa", b =>
                {
                    b.HasOne("PortalTrabajo.Model.Empresa", "Empresa")
                        .WithOne("ContactosEmpresa")
                        .HasForeignKey("PortalTrabajo.Model.ContactosEmpresa", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Educacion", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatGradosAcademico", "GradoAcademico")
                        .WithMany("Educacions")
                        .HasForeignKey("GradoAcademicoId")
                        .IsRequired()
                        .HasConstraintName("FK_Educacion_Grado");

                    b.HasOne("PortalTrabajo.Model.PerfilesEstudiante", "Perfil")
                        .WithMany("Educacions")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Educacion_Perfil");

                    b.Navigation("GradoAcademico");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Empresa", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatSector", "SectorNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("SectorId")
                        .HasConstraintName("FK_Empresas_Sector");

                    b.HasOne("PortalTrabajo.Model.Usuario", "Usuario")
                        .WithOne("Empresa")
                        .HasForeignKey("PortalTrabajo.Model.Empresa", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Empresas_Usuario");

                    b.Navigation("SectorNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalTrabajo.Model.EstudianteHabilidade", b =>
                {
                    b.HasOne("PortalTrabajo.Model.Habilidade", "Habilidad")
                        .WithMany("EstudianteHabilidades")
                        .HasForeignKey("HabilidadId")
                        .IsRequired()
                        .HasConstraintName("FK_Hab_Habilidad");

                    b.HasOne("PortalTrabajo.Model.PerfilesEstudiante", "Perfil")
                        .WithMany("EstudianteHabilidades")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Hab_Perfil");

                    b.Navigation("Habilidad");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PortalTrabajo.Model.EstudianteIdioma", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatNivelesIdioma", "Nivel")
                        .WithMany("EstudianteIdiomas")
                        .HasForeignKey("NivelId")
                        .IsRequired()
                        .HasConstraintName("FK_Idiomas_Nivel");

                    b.HasOne("PortalTrabajo.Model.PerfilesEstudiante", "Perfil")
                        .WithMany("EstudianteIdiomas")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Idiomas_Perfil");

                    b.Navigation("Nivel");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PortalTrabajo.Model.ExperienciasLaborale", b =>
                {
                    b.HasOne("PortalTrabajo.Model.PerfilesEstudiante", "Perfil")
                        .WithMany("ExperienciasLaborales")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExpLab_Perfil");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PortalTrabajo.Model.OfertaHabilidade", b =>
                {
                    b.HasOne("PortalTrabajo.Model.Habilidade", "Habilidad")
                        .WithMany("OfertaHabilidades")
                        .HasForeignKey("HabilidadId")
                        .IsRequired()
                        .HasConstraintName("FK_OfertaHab_Habilidad");

                    b.HasOne("PortalTrabajo.Model.OfertasLaborale", "Oferta")
                        .WithMany("OfertaHabilidades")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfertaHab_Oferta");

                    b.Navigation("Habilidad");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("PortalTrabajo.Model.OfertasLaborale", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatDistrito", "Distrito")
                        .WithMany("OfertasLaborales")
                        .HasForeignKey("DistritoId")
                        .HasConstraintName("FK_Ofertas_Distrito");

                    b.HasOne("PortalTrabajo.Model.Empresa", "Empresa")
                        .WithMany("OfertasLaborales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ofertas_Empresa");

                    b.HasOne("PortalTrabajo.Model.CatGenero", "Genero")
                        .WithMany("OfertasLaborales")
                        .HasForeignKey("GeneroId")
                        .HasConstraintName("FK_Ofertas_Genero");

                    b.HasOne("PortalTrabajo.Model.CatTiposLicencium", "Licencia")
                        .WithMany("OfertasLaborales")
                        .HasForeignKey("LicenciaId")
                        .HasConstraintName("FK_Ofertas_Licencia");

                    b.HasOne("PortalTrabajo.Model.CatModalidade", "Modalidad")
                        .WithMany("OfertasLaborales")
                        .HasForeignKey("ModalidadId")
                        .IsRequired()
                        .HasConstraintName("FK_Ofertas_Modalidad");

                    b.HasOne("PortalTrabajo.Model.CatTiposContrato", "TipoContrato")
                        .WithMany("OfertasLaborales")
                        .HasForeignKey("TipoContratoId")
                        .HasConstraintName("FK_Ofertas_Contrato");

                    b.Navigation("Distrito");

                    b.Navigation("Empresa");

                    b.Navigation("Genero");

                    b.Navigation("Licencia");

                    b.Navigation("Modalidad");

                    b.Navigation("TipoContrato");
                });

            modelBuilder.Entity("PortalTrabajo.Model.PerfilesEstudiante", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatCarrera", "Carrera")
                        .WithMany("PerfilesEstudiantes")
                        .HasForeignKey("CarreraId")
                        .HasConstraintName("FK_PerfilesEstudiantes_Carrera");

                    b.HasOne("PortalTrabajo.Model.Usuario", "Usuario")
                        .WithOne("PerfilesEstudiante")
                        .HasForeignKey("PortalTrabajo.Model.PerfilesEstudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilesEstudiantes_Usuario");

                    b.Navigation("Carrera");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Postulacione", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatEstadosPostulacion", "Estado")
                        .WithMany("Postulaciones")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Postulaciones_Estados");

                    b.HasOne("PortalTrabajo.Model.OfertasLaborale", "Oferta")
                        .WithMany("Postulaciones")
                        .HasForeignKey("OfertaId")
                        .IsRequired()
                        .HasConstraintName("FK_Postulaciones_Ofertas");

                    b.HasOne("PortalTrabajo.Model.PerfilesEstudiante", "Perfil")
                        .WithMany("Postulaciones")
                        .HasForeignKey("PerfilId")
                        .IsRequired()
                        .HasConstraintName("FK_Postulaciones_Perfiles");

                    b.Navigation("Estado");

                    b.Navigation("Oferta");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PortalTrabajo.Model.ProyectosEstudiante", b =>
                {
                    b.HasOne("PortalTrabajo.Model.PerfilesEstudiante", "Perfil")
                        .WithMany("ProyectosEstudiantes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Proyectos_Perfil");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Usuario", b =>
                {
                    b.HasOne("PortalTrabajo.Model.CatRole", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatCarrera", b =>
                {
                    b.Navigation("PerfilesEstudiantes");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatDepartamento", b =>
                {
                    b.Navigation("CatMunicipios");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatDistrito", b =>
                {
                    b.Navigation("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatEstadosPostulacion", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatGenero", b =>
                {
                    b.Navigation("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatGradosAcademico", b =>
                {
                    b.Navigation("Educacions");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatModalidade", b =>
                {
                    b.Navigation("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatMunicipio", b =>
                {
                    b.Navigation("CatDistritos");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatNivelesIdioma", b =>
                {
                    b.Navigation("EstudianteIdiomas");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatRole", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatSector", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatTiposContrato", b =>
                {
                    b.Navigation("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.CatTiposLicencium", b =>
                {
                    b.Navigation("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Empresa", b =>
                {
                    b.Navigation("ContactosEmpresa");

                    b.Navigation("OfertasLaborales");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Habilidade", b =>
                {
                    b.Navigation("EstudianteHabilidades");

                    b.Navigation("OfertaHabilidades");
                });

            modelBuilder.Entity("PortalTrabajo.Model.OfertasLaborale", b =>
                {
                    b.Navigation("OfertaHabilidades");

                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("PortalTrabajo.Model.PerfilesEstudiante", b =>
                {
                    b.Navigation("Educacions");

                    b.Navigation("EstudianteHabilidades");

                    b.Navigation("EstudianteIdiomas");

                    b.Navigation("ExperienciasLaborales");

                    b.Navigation("Postulaciones");

                    b.Navigation("ProyectosEstudiantes");
                });

            modelBuilder.Entity("PortalTrabajo.Model.Usuario", b =>
                {
                    b.Navigation("Empresa");

                    b.Navigation("PerfilesEstudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
